import { ArrowRight, Heart, Quote, ShieldCheck, Sunrise } from "lucide-react";
import { Link } from "wouter";
import { ContactStrip, imageUrls, PageFrame, PageHero, SectionIntro } from "@/components/SiteLayout";

const values = [
  { icon: Heart, title: "Compassion", body: "We choose presence over distance, meeting people with dignity, patience, and practical love." },
  { icon: Sunrise, title: "Formation", body: "We make space for people to become more like Christ through Scripture, community, and service." },
  { icon: ShieldCheck, title: "Faithfulness", body: "We keep showing up for our neighbours, especially when the work is quiet or unseen." },
];

export default function About() {
  return <PageFrame><main><PageHero eyebrow="Our story" title="A steady light in the neighbourhood." body="Christian Trinity Centre began with a simple conviction: when people grow in Christ together, entire communities become more hopeful." image={imageUrls.prayer} /><section className="section-pad"><div className="container grid gap-14 lg:grid-cols-[0.8fr_1.2fr]"><SectionIntro eyebrow="Why we exist" title="The church is a people, not just a place." body="From our earliest gatherings to the community we are becoming today, our heart has stayed the same: to create a welcoming, rooted, and outward-looking family of faith." /><div className="space-y-7 text-base leading-8 text-[var(--muted-ink)]"><p>In Kilimani and Makhonge, Christian Trinity Centre serves as a spiritual home, a learning environment, and a practical partner to families. We bring together worship, education, and community ministry because each one strengthens the other.</p><p>Our doors are open to people at every stage of the journey — those who have followed Jesus for years, those who are asking honest questions, and everyone looking for a place to belong.</p><blockquote className="relative border-l-2 border-[var(--gold)] pl-6 font-serif text-2xl leading-10 text-[var(--ink)]"><Quote className="absolute -left-3 -top-5 h-6 w-6 bg-[var(--cream)] text-[var(--gold-dark)]" />“We want every person who walks through our doors to leave with more courage, more hope, and a clearer sense of God’s love.”</blockquote></div></div></section><section className="section-pad bg-[var(--paper)]"><div className="container"><SectionIntro eyebrow="What guides us" title="Our values are lived, not framed." body="They shape how we welcome, teach, lead, and serve." /><div className="mt-12 grid gap-5 md:grid-cols-3">{values.map(({ icon: Icon, title, body }) => <article key={title} className="value-card"><Icon className="h-7 w-7 text-[var(--gold-dark)]" /><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-[var(--muted-ink)]">{body}</p></article>)}</div></div></section><section className="section-pad"><div className="container grid gap-12 lg:grid-cols-2 lg:items-center"><div className="image-frame"><img src={imageUrls.teaching} alt="A teacher encouraging students" /></div><div><p className="eyebrow">Our posture</p><h2 className="section-title mt-3">Open hands. Open hearts. Open doors.</h2><p className="mt-6 text-base leading-8 text-[var(--muted-ink)]">We are a community learning to hold conviction and welcome together. That means asking good questions, caring for the whole person, and using what we have to bless the people around us.</p><Link href="/ministries" className="text-link mt-8">See how we serve <ArrowRight className="h-4 w-4" /></Link></div></div></section><ContactStrip /></main></PageFrame>;
}
