import { CalendarDays, Clock, MapPin, Users } from "lucide-react";
import { Link } from "wouter";
import { ContactStrip, EventCard, imageUrls, PageFrame, PageHero, SectionIntro } from "@/components/SiteLayout";

const events = [
  { date: "14 SEP", title: "Community Sunday", type: "Gathering", detail: "Worship, shared lunch, and stories from the people and partners who make our neighbourhood stronger." },
  { date: "21 SEP", title: "Youth creative lab", type: "Youth", detail: "Music, design, conversation, and a practical workshop for young people aged 13–21." },
  { date: "04 OCT", title: "Foundations of faith", type: "Course", detail: "A four-week conversation for anyone curious about the Christian story. No prior knowledge needed." },
  { date: "12 OCT", title: "School open morning", type: "Education", detail: "Meet our teachers, explore the learning spaces, and discover the heart behind Trinity Academy." },
  { date: "26 OCT", title: "Neighbourhood care day", type: "Community", detail: "Join a practical day of clean-up, family support, and shared meals across our local community." },
];

export default function Events() {
  return <PageFrame><main><PageHero eyebrow="Events & gatherings" title="Make room for what matters." body="From Sunday worship to neighbourhood care days, our calendar is full of moments to connect, learn, and serve." image={imageUrls.worship} /><section className="section-pad"><div className="container grid gap-14 lg:grid-cols-[0.75fr_1.25fr]"><div><SectionIntro eyebrow="This season" title="Come for an event. Stay for the people." body="Our gatherings are relaxed, welcoming, and designed to help you take one easy next step into community." /><div className="mt-8 rounded-2xl bg-[var(--teal)] p-6 text-white"><CalendarDays className="h-6 w-6 text-[var(--gold)]" /><p className="mt-5 text-sm leading-7 text-white/70">Most events happen at our Kilimani and Makhonge locations. Reach out before you come and we will help you find the right room.</p><Link href="/contact" className="text-link mt-6 text-white">Ask about an event <span>→</span></Link></div></div><div className="space-y-4">{events.map((event) => <EventCard key={event.title} {...event} />)}</div></div></section><section className="section-pad bg-[var(--paper)]"><div className="container grid gap-10 md:grid-cols-3"><div className="flex gap-4"><Clock className="mt-1 h-5 w-5 text-[var(--gold-dark)]" /><div><h3 className="font-semibold">Sunday worship</h3><p className="mt-2 text-sm leading-6 text-[var(--muted-ink)]">Every Sunday at 9:00 AM. A joyful, intergenerational gathering.</p></div></div><div className="flex gap-4"><Users className="mt-1 h-5 w-5 text-[var(--gold-dark)]" /><div><h3 className="font-semibold">Youth Saturdays</h3><p className="mt-2 text-sm leading-6 text-[var(--muted-ink)]">Every Saturday at 3:00 PM. Safe, creative, and full of energy.</p></div></div><div className="flex gap-4"><MapPin className="mt-1 h-5 w-5 text-[var(--gold-dark)]" /><div><h3 className="font-semibold">Two neighbourhoods</h3><p className="mt-2 text-sm leading-6 text-[var(--muted-ink)]">Kilimani and Makhonge. Contact us for directions and accessibility details.</p></div></div></div></section><ContactStrip /></main></PageFrame>;
}
