import { ArrowRight, BookOpen, HeartHandshake, Music2, Users, Wheat } from "lucide-react";
import { Link } from "wouter";
import { ContactStrip, imageUrls, PageFrame, PageHero, SectionIntro } from "@/components/SiteLayout";

const ministryCards = [
  { icon: HeartHandshake, title: "Church & worship", image: imageUrls.worship, body: "Gather with us for worship that is grounded in Scripture, generous in spirit, and honest about the joys and challenges of life with God." },
  { icon: BookOpen, title: "Trinity Academy", image: imageUrls.teaching, body: "Our school supports learners to grow in knowledge, confidence, character, and a sense of responsibility for the world they will shape." },
  { icon: Users, title: "Youth & families", image: imageUrls.youth, body: "Through mentoring, creative gatherings, and shared experiences, we help young people find their voice and their people." },
  { icon: Wheat, title: "Community care", image: imageUrls.community, body: "We partner with local families and leaders to respond to practical needs with humility, consistency, and care." },
];

export default function Ministries() {
  return <PageFrame><main><PageHero eyebrow="Our ministries" title="Faith with sleeves rolled up." body="Every ministry is a practical expression of our hope in Christ — making room for people to grow, connect, and serve." image={imageUrls.community} /><section className="section-pad"><div className="container"><SectionIntro eyebrow="Find your place" title="There are many ways to take part." body="Start where you are. Come curious, come tired, come ready to help — there is room for you here." /><div className="mt-12 grid gap-5 md:grid-cols-2">{ministryCards.map(({ icon: Icon, title, image, body }) => <article key={title} className="ministry-detail-card group"><div className="relative h-64 overflow-hidden"><img src={image} alt="" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/55 to-transparent" /><div className="absolute bottom-5 left-5 flex items-center gap-3 text-white"><span className="icon-circle icon-circle-light"><Icon className="h-5 w-5" /></span><h3 className="text-2xl font-semibold">{title}</h3></div></div><div className="p-6"><p className="text-sm leading-7 text-[var(--muted-ink)]">{body}</p><Link href="/contact" className="text-link mt-6">Ask a question <ArrowRight className="h-4 w-4" /></Link></div></article>)}</div></div></section><section className="teal-section section-pad"><div className="container grid gap-12 lg:grid-cols-[1fr_0.9fr] lg:items-center"><div><p className="eyebrow eyebrow-light">A life of service</p><h2 className="section-title text-white">Small acts. Deep roots. Real impact.</h2><p className="mt-5 max-w-xl text-base leading-8 text-white/70">We believe transformation often looks ordinary: a child encouraged, a neighbour remembered, a young person given a safe place to ask hard questions.</p><Link href="/contact" className="button button-gold mt-8">Get involved <ArrowRight className="h-4 w-4" /></Link></div><div className="grid grid-cols-2 gap-3"><div className="impact-tile"><Music2 /><strong>Worship</strong><span>Gathering with joy</span></div><div className="impact-tile"><Users /><strong>Belonging</strong><span>Growing together</span></div><div className="impact-tile"><BookOpen /><strong>Learning</strong><span>Equipping futures</span></div><div className="impact-tile"><HeartHandshake /><strong>Serving</strong><span>Loving our neighbours</span></div></div></div></section><ContactStrip /></main></PageFrame>;
}
